
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-docker
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-docker
  template:
    metadata:
      labels:
        app: hello-docker
    spec:
      containers:
        - name: hello-docker
          image: localhost:5000/hello-docker:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
